name: Changelog and version

on:
  workflow_call:

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            CHANGELOG.md
            **/version.rb

      - name: Ensure changelog has been updated
        if: ${{ !contains(steps.changed-files.outputs.modified_files, 'CHANGELOG.md') }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('CHANGELOG.md was not updated')

      - name: Ensure version.rb has been updated
        if: ${{ !contains(steps.changed-files.outputs.modified_files, 'version.rb') }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('version.rb was not updated')
